# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ESLint

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        npm i eslint eslint-config-airbnb-base babel-eslint eslint-plugin-import -D
    
    - name: ESLint
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review
        workdir: 'src/'
        eslint_flags: '../.eslintrc.js'
        fail_on_error: true
        level: error
